version: '3.8'

services:
  host-app:
    build: ./host-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  products-remote:
    build: ./products-remote
    ports:
      - "3001:3001"
    networks:
      - app-network

  basket-remote:
    build: ./basket-remote
    ports:
      - "3002:3002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
